%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_09-17-08.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/13 09:19:02

%% Initialize variables.
filename = 'C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_09-17-08.csv';
delimiter = ';';
startRow = 2;
endRow = 406;

%% Format for each line of text:
%   column1: double (%f)
%	column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%*s%f%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow-startRow+1, 'Delimiter', delimiter, 'HeaderLines', startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
HallVoltageConstantTorque = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow endRow formatSpec fileID dataArray ans;

p = polyfit(HallVoltageConstantTorque(:,1),HallVoltageConstantTorque(:,2),3);
y1 = polyval(p,HallVoltageConstantTorque(:,1));
stddev = std(HallVoltageConstantTorque(:,2)-y1);

plot(HallVoltageConstantTorque(:,1),HallVoltageConstantTorque(:,2)-y1)