%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_09-02-25.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/13 09:04:05

%% Initialize variables.
filename = 'C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_09-02-25.csv';
delimiter = ';';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column7: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%*s%f%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
HallVoltageNoiseMove = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
a = 0.00105/0.007; %Time step*filter frequency
yfilt = filter([1-a a-1],[1 a-1], HallVoltageNoiseMove(:,2));
plot(yfilt)