%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_10-20-04.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/13 10:30:16

%% Initialize variables.
filename = 'C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_10-20-04.csv';
delimiter = ';';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column11: double (%f)
%   column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%*s%*s%f%f%*s%f%f%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
timestamps = dataArray{:, 1};
encoder_paddle_veldegs = dataArray{:, 2};
encoder_paddle_vel2degs = dataArray{:, 3};
hall_paddle_veldegs = dataArray{:, 4};
hall_paddle_vel2degs = dataArray{:, 5};


%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

a = 0.00105/2; %Time step*filter frequency
encoder_paddle_veldegs = filter(a,[1 a-1], encoder_paddle_veldegs);
encoder_paddle_vel2degs = filter(a,[1 a-1], encoder_paddle_vel2degs);
hall_paddle_veldegs = filter(a,[1 a-1], hall_paddle_veldegs);
hall_paddle_vel2degs = filter(a,[1 a-1], hall_paddle_vel2degs);
figure
plot(encoder_paddle_veldegs)
hold on
plot(encoder_paddle_vel2degs)
plot(hall_paddle_veldegs)
plot(hall_paddle_vel2degs)
a = 0.00105/0.001;
encoder_paddle_veldegs = filter([1-a a-1],[1 a-1], encoder_paddle_veldegs);
encoder_paddle_vel2degs = filter([1-a a-1],[1 a-1], encoder_paddle_vel2degs);
hall_paddle_veldegs = filter([1-a a-1],[1 a-1], hall_paddle_veldegs);
hall_paddle_vel2degs = filter([1-a a-1],[1 a-1], hall_paddle_vel2degs);

encoderv2sample_std = std(encoder_paddle_veldegs)
encoderv3sample_std = std(encoder_paddle_vel2degs)
hallv2sample_std = std(hall_paddle_veldegs)
hallv3sample_std = std(hall_paddle_vel2degs)