%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_10-19-39.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/03/13 10:24:17

%% Initialize variables.
filename = 'C:\Users\Hannes\Desktop\Master\HapticHumanRobotInterfaces\LogFiles\log_2018-03-13_10-19-39.csv';
delimiter = ';';
startRow = 2;

%% Format for each line of text:
%   column1: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column11: double (%f)
%   column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%*s%*s%*s%*s%*s%*s%f%f%*s%f%f%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
VelocityNoise = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

encoderv2sample_std = std(VelocityNoise(:,2))
encoderv3sample_std = std(VelocityNoise(:,3))
hallv2sample_std = std(VelocityNoise(:,4))
hallv3sample_std = std(VelocityNoise(:,5))